IA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('IAs.urls', namespace = 'IAs')),
]

urlpatterns+= static(settings.STATIC_URL, document_root  = settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root  = settings.MEDIA_ROOT)

IAs/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_view

app_name = 'IAs'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('homefrotas/', Homefrotas.as_view(), name='homefrotas'),
    path('homefrotas/escala/remessa/', Remessas.as_view(), name='remessa'),
    path('homefrotas/escala/remessa/upload/', simple_upload, name='upload'),
    path('homefrotas/disponibilidade/<int:pk>', Detalhesfrotas.as_view(), name='detalhesfrotas'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('homefrotas/disponibilidade/', disponibilidade, name='disponibilidade'),
    path('homefrotas/escala/', escala, name='escala'),
    path('homefrotas/escala/download/', download_escala, name='downloadescala'),
    path('homefrotas/relatorios/download/', Relatorios.as_view(), name='relatorios'),
    path('homefrotas/colaboradores/', controle_func, name='colaboradores'),
]

IAs/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime, timedelta
# Create your models here.

class Usuario(AbstractUser):
    pass

class Frota(models.Model):
    lista = (('DISPONÍVEL', 'DISPONÍVEL'),
             ('EM ROTA', 'EM ROTA'),
             ('MANUTENÇÃO', 'MANUTENÇÃO'),
             )
    empresas = [
            ('IPIRANGA', 'IPIRANGA'),
        ('SHELL', 'SHELL'),
    ]
    numero = models.IntegerField()
    imagem = models.ImageField(upload_to = 'foto_frota', default= 'padrão.png')
    placa = models.CharField(max_length = 8)
    tipo = models.CharField(max_length = 20)
    bau = models.CharField(max_length = 20)
    capacidade = models.IntegerField()
    motorista = models.ForeignKey('Colaboradores', related_name= 'colaboradores', on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=lista, default='DISPONÍVEL')
    empresa = models.CharField(max_length=10, choices=empresas, default= 'IPIRANGA' )

    def __str__(self):
        return str(self.numero)

class Colaboradores(models.Model):
    funcoes = [('OPERADOR','OPERADOR'),
              ('AJUDANTE','AJUDANTE'),
              ('MOTORISTA VUC', 'MOTORISTA VUC'),
              ('MOTORISTA MÉDIO','MOTORISTA MÉDIO'),
              ('MOTORISTA PESADO', 'MOTORISTA PESADO'),
              ('MOTORISTA MONITOR', 'MOTORISTA MONITOR'),

              ]
    lista_status = [('DISPONÍVEL', 'DISPONÍVEL'),
                    ('EM ROTA', 'EM ROTA'),
                    ('FÉRIAS', 'FÉRIAS'),
                    ('AFASTADO', 'AFASTADO'),
                    ('ATESTADO', 'ATESTADO'),
                    ('FOLGA', 'FOLGA'),
                    ]
    lista_hora = [('NULO',' NULO'),
                  ('POSITIVO', 'POSITIVO'),
                  ('NEGATIVO', 'NEGATIVO'),
                    ]
    empresas = [
        ('IPIRANGA', 'IPIRANGA'),
        ('SHELL', 'SHELL'),
    ]

    nome = models.CharField(max_length=100)
    nome_guerra = models.CharField(max_length=50)
    funcao = models.CharField(max_length=20, choices=funcoes)
    status = models.CharField(max_length=20, choices=lista_status, default='DISPONÍVEL')
    periodo = models.CharField(max_length=10, blank=True, null=True)
    horas = models.CharField(max_length=90, blank=True, null=True)
    tempo_s = models.FloatField(blank=True)
    status1 = models.CharField(max_length=20, choices=lista_hora, default='NULO')
    empresa = models.CharField(max_length=20, choices=empresas, default='IPIRANGA')
    observacoes = models.CharField(max_length=100, null=True, blank=True)

    def save(self, *args, **kwargs):
        hora = int(self.horas[:2])
        minutos = int(self.horas[3:5])

        segundos = hora * 3600 + minutos * 60
        if segundos == '':
            self.status1 = 'NULO'

        if self.status1 == 'NEGATIVO':
            self.tempo_s = -segundos
        else:
            self.tempo_s = segundos
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nome_guerra

class Escala(models.Model):
    data = models.DateField(default= datetime.utcnow)
    remessa = models.CharField(max_length=100)
    frota = models.IntegerField()
    placa = models.CharField(max_length=10)
    tipo_carga = models.CharField(max_length=5)
    peso = models.IntegerField()
    entregas = models.IntegerField(default=0)
    distancia = models.IntegerField(default=0)
    motorista = models.CharField(max_length=30)
    ajudante = models.CharField(max_length=30)
    viagem = models.CharField(max_length=3)
    status = models.CharField(max_length=10, default ='EM ENTREGA')
    observacao = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return str(self.remessa)

class ArqRemessa(models.Model):
    arquivo = models.FileField(upload_to='remessas')

    def __str__(self):
        return str(self.arquivo)

class Remessa(models.Model):
    remessa = models.CharField(max_length=10)
    placa = models.CharField(max_length=10)
    peso = models.IntegerField(default= 0)
    categoria = models.CharField(max_length=10, default='N/D')
    entregas = models.IntegerField(default=0)
    distancia = models.IntegerField(default=0)
    status = models.CharField(max_length=10, default= 'DISPONÍVEL')

    def __str__(self):
        return str(self.remessa)

IAs/forms.py
from django.contrib.auth.forms import UserCreationForm, forms
from .models import *

class CriarContaForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')

IAs/views.py
import os
import pandas as pd
from .forms import *
from .models import *
from .resources import RemessaResources
from datetime import date, datetime
from django.contrib import messages
from django.views.generic import *
from tablib import Dataset
from django.http import HttpResponse, JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class Homepage(TemplateView):
    template_name = 'homepage.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('IAs:homefrotas')
        else:
            return super().get(request, *args, **kwargs)

class Criarconta(FormView):
    template_name = 'criarconta.html'
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('IAs:login')

class Homefrotas(LoginRequiredMixin, ListView):
    template_name = 'homefrotas.html'
    model = Frota

class Detalhesfrotas(LoginRequiredMixin, DetailView):
    template_name = 'detalhefrotas.html'
    model = Frota

    @method_decorator(csrf_exempt, name='dispatch')
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            frota = request.POST.get('frota_man')
            stts = Frota.objects.filter(numero = frota)
            print(frota, stts)
            stts.update(status = 'MANUTENÇÃO')

        return redirect('IAs:disponibilidade')

class Relatorios(LoginRequiredMixin, TemplateView):
    template_name = 'relatorios.html'

    @method_decorator(csrf_exempt, name='dispatch')
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            data = request.POST.get('datahorariosaida')
            funcao = request.POST.get('funcao_down')
            status = request.POST.get('status_down')
            empresa = request.POST.get('empresa_down')

            if data != None:
                return download_horario_saida(request, data)
            elif funcao != None and status != None and empresa != None:
                return download_colaboradores(request, funcao, status, empresa)
            else:
                return download_disponibilidade(request)
        return redirect('IAs:homefrotas')

class Remessas(TemplateView):
    template_name = 'remessa.html'

def simple_upload(request):
    if request.method == 'POST':
        remessa_resources = RemessaResources()
        dataset = Dataset()
        new_remessa = request.FILES['myfile']

        if not new_remessa.name.endswith('xlsx'):
            messages.info(request,'wrong format')
            return redirect('IAs:homefrotas')
        import_data = dataset.load(new_remessa.read(), format='xlsx')
        for data in import_data:
            if data[0] == None or Remessa.objects.filter(remessa = str(data[0]).replace('AMPM.','')).exists():
                pass
                print(data[0], " - ", data[1], " - ",data[4], " - ", data[5], " - ", data[6], " - ", data[7])
            else:
                value = Remessa(Remessa.objects.count(),
                    str(data[0]).replace('AMPM.',''),
                    str(data[4]),
                    str(data[5]),
                    str(data[1]),
                    str(data[6]),
                    str(data[7]).split('.')[0]
                    )
                value.save()
    return render(request, 'remessa.html')
def disponibilidade(request):
    veiculos = Frota.objects.all()
    escalas = Escala.objects.filter(status='EM ENTREGA').all()
    manutencao = Frota.objects.filter(status = 'MANUTENÇÃO').all()

    if request.method == 'POST':

        status = request.POST.get('selectstatus1')

        if status == 'EM ROTA':
            pass
        else:
            frota = request.POST.get('selectfrotas1')
            remessa = request.POST.get('dispRemessa1')
            stts = Escala.objects.filter(remessa=remessa).all()
            stts.update(status='ENTREGUE')
            remessa = str(remessa).replace(' ','').split(';')

            for rem in remessa:
                remessas = Remessa.objects.filter(remessa=rem).all()
                remessas.update(status='ENTREGUE')

            motorista = request.POST.get('dispMotorista1')
            ajudante = request.POST.get('dispAjudante1')

            frotas = Frota.objects.filter(numero = frota)
            frotas.update(status=status)
            motoristas = Colaboradores.objects.filter(nome_guerra=motorista).all()
            motoristas.update(status='DISPONÍVEL')
            ajudantes = Colaboradores.objects.filter(nome_guerra = ajudante).all()
            ajudantes.update(status='DISPONÍVEL')
        return redirect('IAs:disponibilidade')

    return render(request, 'disponibilidade.html', {'escalas': escalas, 'veiculos': veiculos, 'manutencao': manutencao})

def escala(request):
    # Bancos que alimentam dados da página de escala
    periodos = Colaboradores.objects.all()
    listas = Frota.objects.filter(status = 'DISPONÍVEL', empresa = 'IPIRANGA').all()
    escalas = Escala.objects.order_by('-data').all()
    ajudantes = Colaboradores.objects.order_by('status1', 'tempo_s').reverse().filter(status = 'DISPONÍVEL').all()
    motoristas = Colaboradores.objects.order_by('status1', 'tempo_s').reverse().all()

    # Prazo de folgas, atestados, afastamentos e férias...

    # Paginação
    paginator = Paginator(escalas, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    remessas = Remessa.objects.filter(status = 'DISPONÍVEL')

    try:
        # Tratar período ausente baseado no dia da escala
        for i in periodos:
            if i.periodo == None or i.periodo == '':
                pass
            else:
                data = i.periodo
                data_tratada = datetime.strptime(str(data), "%Y-%m-%d").date()

                if data_tratada < date.today():
                    novo_periodo = Colaboradores.objects.filter(nome=i.nome)
                    novo_periodo.update(status='DISPONÍVEL', periodo=None)
    except:
        pass

    # Adicionar no banco de dados
    if request.method == 'POST':
        remessa = request.POST.get('remessa1')
        # Verificar se há encaixe
        if len(remessa) > 6:
            rem = str(remessa).split(';')
            for rem1 in rem:
                add = Remessa.objects.filter(remessa = rem1).all()
                add.update(status = 'EM ROTA')
        else:
            pass

        frota = request.POST.get('frota1')
        placa = request.POST.get('placa1')
        peso = request.POST.get('peso1')
        tipo = request.POST.get('tipo1')
        motorista = request.POST.get('motorista1')
        ajudante = request.POST.get('ajudante1')
        viagem = request.POST.get('viagem1')
        entregas = request.POST.get('entregas1')
        distancia = request.POST.get('distancia1')
        obs = request.POST.get('obs')

        escala = Escala(remessa = remessa, frota = frota, placa = placa, peso = peso, tipo_carga = tipo, motorista = motorista, ajudante = ajudante, viagem = viagem, entregas = entregas, distancia = distancia, observacao = obs)

        # Verificar se os campos abaixo estão vazios evitar um erro
        if frota == '' or placa == '' or peso == '' or ajudante == '' or motorista == '':
            pass
        else:

            # Mudança de status no Banco de Dados
            disp = Frota.objects.filter(numero = frota)
            disp.update(status = 'EM ROTA')

            mot = Colaboradores.objects.filter(nome_guerra = motorista)
            mot.update(status = 'EM ROTA')

            if ajudante == '-' or ajudante == 'CHAPA':
                pass
            else:
                aj = Colaboradores.objects.filter(nome_guerra = ajudante)
                aj.update(status = 'EM ROTA')

            rem = Remessa.objects.filter(remessa = remessa)
            rem.update(status ='EM ROTA')

            # Não deixar cadastrar duas vezes os mesmos dados
            if Escala.objects.filter(remessa = remessa).exists():
                pass
            else:
                escala.save()
            return redirect('IAs:escala')
    else:
        pass
    return render(request, 'escala.html', {'listas':listas, 'escalas':escalas, 'ajudantes': ajudantes, 'motoristas':motoristas, 'remessas': remessas, 'page_obj': page_obj})

def download_escala(request):
    try:
        if request.method == 'POST':
            data = request.POST.get('data1')

            queryset = Escala.objects.filter(data = data).all()

            # Crie um DataFrame com os dados do modelo
            df = pd.DataFrame(list(queryset.values()))

            df = df[['remessa','tipo_carga','frota','placa','motorista', 'viagem','ajudante']]
            df = df.rename(columns={'remessa':'REMESSA', 'tipo_carga': 'CATEGORIA', 'frota': 'FROTA', 'placa': 'PLACA', 'motorista': 'MOTORISTA', 'viagem': 'VIAGEM', 'ajudante': 'AJUDANTE' })

            # Defina o caminho e nome do arquivo Excel de saída
            # caminho = r"\Downloads"
            output_filename = f'\Escala-{data}.xlsx'

            # Exporte o DataFrame para um arquivo Excel
            df.to_excel(output_filename, index=False)

            # Abra o arquivo Excel para download
            with open(output_filename, 'rb') as file:
                response = HttpResponse(file.read(),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
                response['Content-Disposition'] = 'attachment; filename="{}"'.format(output_filename)
            return response
    except:
        return redirect('IAs:escala')
    return render(request, 'download_escala.html')

def download_disponibilidade(request):
    try:

IAs/templates/criarconta.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Criar Conta
{% endblock %}

{% block content %}

    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
               {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Crie uma conta para continuar</legend>
                   {{ form|crispy }}
                </fieldset>
                <button class="bg-blue-600 py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
            </form>
        </div>
    </header>

{% endblock %}

IAs/templates/detalhefrotas.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Detalhes Frotas
{% endblock %}

{% block content %}
<form name="FormMan" id="FormMan" method="POST" action="{% url 'IAs:detalhesfrotas' frota.pk %}">
    {% csrf_token %}
    <img src="{% static frota.imagem %}" class="bg-center">
    <div class="container py-5 text-white">
        <h1>Detalhes:</h1>
        <br>
        <table class="table table-bordered border-white text-white text-center">
            <thead>
                <tr>
                    <th scope="col">Frota</th>
                    <th scope="col">Placa</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Baú</th>
                    <th scope="col">Capacidade</th>
                    <th scope="col">Motorista</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <input id="frota_man" name="frota_man" value="{{frota.numero}}" class="input bg-black text-white text-center w-8" readonly>
                    </td>
                    <td>{{frota.placa}}</td>
                    <td>{{frota.tipo}}</td>
                    <td>{{frota.bau}}</td>
                    <td>{{frota.capacidade}} Kg </td>
                        {% if frota.motorista == '-' %}
                            <td>Não Definido</td>
                        {% else %}
                            <td>{{frota.motorista}}</td>
                        {% endif %}
            </tbody>
            <script src="/static/js/custom.js"></script>
        </table>
        <br>
        <span>
            <h1 id="status">Status: {{frota.status}} </h1>
                <br>
            <button id="btn_man" class="btn btn-primary" style="display: block;">Manutenção</button>
        </span>
    </div>
</form>
{% endblock %}

IAs/templates/download_escala.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Download Escala
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase justify-center bg-no-repeat bg-cover bg-center"  style="background-image: url('{% static 'image/FundoDownloadEscala.jpg' %}');">
    <form name="FormDownloadEscala" id="FormDownloadEscala" method="POST" action="" class="form-horizontal" autocomplete="off">
        {% csrf_token %}
        <div class="container text-center p-10">
        <div class="row align-items-center">
            <div class="col">
                <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
            </div>
            <div class="col">
                <label class="label">Escolha uma Data:</label>
                    <br><br><br>
                <span class="input">
                    <input name="data1" id="data1" maxlength="10" required class="rounded-md text-center text-black" type="date">
                    <input type="button">
                </span>
                    <br><br><br>
                <button class="btn btn-primary">Download</button>
            </div>
            <div class="col">

            </div>
        </div>
        </div>
        <script src="/static/js/custom.js"></script>
    </form>
</header>
{% endblock %}

IAs/templates/homefrotas.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Frotas
{% endblock %}
{% block content %}
    <header class="min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-cover bg-center"  style="background-image: url('{% static 'image/FundoHomeFrotas.jpg' %}');">

    </header>
{% endblock %}

IAs/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
HomePage Daudt
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-cover bg-center"  style="background-image: url('{% static 'image/Ford_Cargo.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

        <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
            Escalas semi-automáticas com IA.
        </h1>
        <h3 class="text-xl md:text-xl py-5">
            <a href="{% url 'IAs:login' %}">
                <button class="btn btn-primary">Login</button>
            </a>
        </h3>
    </div>
</header>

<footer class=" px-5 py-20 ">
    <ul class="flex justify-between items-center">

        <li>&copy; 2023</li>
        <li> Criador Carlos Damião </li>
        <li> Feito com Python / Django </li>
    </ul>
</footer>


{% endblock %}

IAs/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block titulo %}
Fazer Login
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-cover bg-center"  style="background-image: url('{% static 'image/Ford_Cargo.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Faça Login para continuar</legend>
                {{ form|crispy }}
            </fieldset>
            <button class="bg-blue-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Fazer Login</button>
        </form>
        <small>
            Não tem uma conta ainda? <p>Solicite o Adm para a criação da mesma</p>
        </small>
    </div>
</header>

{% endblock %}

IAs/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Logout
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-cover bg-center"  style="background-image: url('{% static 'image/Ford_Cargo.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h2 class="text-2xl">Você saiu da sua conta!</h2>
        <div class="flex flex-nowrap justify-center space-x-5 p-5">
        <a href="{% url 'IAs:login' %}"><button class="bg-blue-600  py-1 px-3 text-white md:text-lg rounded-md">Fazer Login</button></a>
<!--            <a href="{% url 'IAs:criarconta' %}"><button class="bg-blue-600 py-1 px-3 text-white md:text-lg rounded-md">Criar uma Conta</button></a>-->
        </div>
    </div>
</header>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">

        <li>&copy; 2021</li>
        <li> Feito com Python (Django)</li>
        <li>Carlos Damião</li>
    </ul>
</footer>
{% endblock %}

IAs/templates/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{message.tags}} m-2" id="msg" role="alert">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

IAs/templates/remessa.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}

Disponibilidade

{% endblock %}

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-cover bg-center"  style="background-image: url('{% static 'image/CarregarRemessas.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
         <form action="{% url 'IAs:upload' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="myfile" class="form-control">
             <br><br>
            <button type="submit" class="btn btn-outline-primary">Upload</button>
             {{ form|crispy }}
         </form>
        </div>
    </header>
{% endblock %}