IA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('IAs.urls', namespace = 'IAs')),
]

urlpatterns+= static(settings.STATIC_URL, document_root  = settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root  = settings.MEDIA_ROOT)

IAs/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_view

app_name = 'IAs'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('homefrotas/', Homefrotas.as_view(), name='homefrotas'),
    path('homefrotas/escala/remessa/', Remessas.as_view(), name='remessa'),
    path('homefrotas/escala/remessa/upload/', simple_upload, name='upload'),
    path('homefrotas/disponibilidade/<int:pk>', Detalhesfrotas.as_view(), name='detalhesfrotas'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('homefrotas/disponibilidade/', disponibilidade, name='disponibilidade'),
    path('homefrotas/escala/', escala, name='escala'),
    path('homefrotas/escala/download/', download_escala, name='downloadescala'),
    path('homefrotas/relatorios/download/', Relatorios.as_view(), name='relatorios'),
    path('homefrotas/colaboradores/', controle_func, name='colaboradores'),
]

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>
        {% block titulo %}

        {% endblock %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js/bootstrap.bundle.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    {% block head %}

    {% endblock %}


</head>
<body class="bg-black text-gray-100 font-primary">
    {% include 'navbar.html' %}
    {% include 'messages.html' %}
    {% block content %}

    {% endblock %}

</body>
</html>

templates/navbar.html
{% load static %}

<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-4/6">
        <a href="/">
           <img src="{% static 'image/daudt.png' %}">
        </a>
    </div>
    {% if user.is_authenticated and view.template_name == 'homefrotas.html' %}
    <div class="mr-2">
        <a href="{% url 'IAs:escala' %}">
            <button class="btn btn-primary">
                Criar Escala
            </button>
        </a>
    </div>
    <div class="mr-2">
        {% if user.is_authenticated and view.template_name == 'homefrotas.html' %}
            <div class="dropdown">
                <button class="btn btn-primary bg-blue-600 dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Mais
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'IAs:disponibilidade' %}">Disponibilidade</a></li>
                    <li><a class="dropdown-item" href="{% url 'IAs:colaboradores' %}">Colaboradores</a></li>
                    <li><a class="dropdown-item" href="{% url 'IAs:relatorios' %}">Relátorios</a></li>
                </ul>
            </div>
        {% endif %}
    </div>
    {% endif %}
    <div class="mr-2">
        {% if user.is_authenticated or view.template_name != 'homepage.html' %}
        <a href="{% url 'IAs:logout' %}">
            <button class="btn btn-primary">
                Sair
            </button>
        </a>
        {% else %}
            {% if view.template_name == 'homepage.html' %}
                <br>
            {% else %}
                <a href="{% url 'IAs:criarconta' %}">
                    <button class="btn btn-primary">
                        Criar Conta
                    </button>
                </a>
            {% endif %}
        {% endif %}
    </div>
</nav>